package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TrCabang generated by hbm2java
 */
public class TrCabang implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String kodeCabang;
	private String kodePropinsi;
	private String kodePerwakilan;
	private String email;
	private String namaCabang;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TrCabang() {
	}

	public TrCabang(String kodeCabang) {
		this.kodeCabang = kodeCabang;
	}

	public TrCabang(String kodeCabang, String kodePropinsi, String kodePerwakilan, String email, String namaCabang,
			Date tglCreate, Date tglUpdate, Integer flag) {
		this.kodeCabang = kodeCabang;
		this.kodePropinsi = kodePropinsi;
		this.kodePerwakilan = kodePerwakilan;
		this.email = email;
		this.namaCabang = namaCabang;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getKodeCabang() {
		return this.kodeCabang;
	}

	public void setKodeCabang(String kodeCabang) {
		this.kodeCabang = kodeCabang;
	}

	public String getKodePropinsi() {
		return this.kodePropinsi;
	}

	public void setKodePropinsi(String kodePropinsi) {
		this.kodePropinsi = kodePropinsi;
	}

	public String getKodePerwakilan() {
		return this.kodePerwakilan;
	}

	public void setKodePerwakilan(String kodePerwakilan) {
		this.kodePerwakilan = kodePerwakilan;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNamaCabang() {
		return this.namaCabang;
	}

	public void setNamaCabang(String namaCabang) {
		this.namaCabang = namaCabang;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
