package entity;


// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TrDiskon generated by hbm2java
 */
public class TrDiskon implements java.io.Serializable {

	private String idDiskon;
	private String kodePelanggan;
	private Integer diskonRapid;
	private Integer diskonJne;
	private Date tglMulaiDiskon;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TrDiskon() {
	}

	public TrDiskon(String idDiskon) {
		this.idDiskon = idDiskon;
	}

	public TrDiskon(String idDiskon, String kodePelanggan, Integer diskonRapid, Integer diskonJne, Date tglMulaiDiskon,
			Date tglCreate, Date tglUpdate, Integer flag) {
		this.idDiskon = idDiskon;
		this.kodePelanggan = kodePelanggan;
		this.diskonRapid = diskonRapid;
		this.diskonJne = diskonJne;
		this.tglMulaiDiskon = tglMulaiDiskon;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getIdDiskon() {
		return this.idDiskon;
	}

	public void setIdDiskon(String idDiskon) {
		this.idDiskon = idDiskon;
	}

	public String getKodePelanggan() {
		return this.kodePelanggan;
	}

	public void setKodePelanggan(String kodePelanggan) {
		this.kodePelanggan = kodePelanggan;
	}

	public Integer getDiskonRapid() {
		return this.diskonRapid;
	}

	public void setDiskonRapid(Integer diskonRapid) {
		this.diskonRapid = diskonRapid;
	}

	public Integer getDiskonJne() {
		return this.diskonJne;
	}

	public void setDiskonJne(Integer diskonJne) {
		this.diskonJne = diskonJne;
	}

	public Date getTglMulaiDiskon() {
		return this.tglMulaiDiskon;
	}

	public void setTglMulaiDiskon(Date tglMulaiDiskon) {
		this.tglMulaiDiskon = tglMulaiDiskon;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
