package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TrKurir generated by hbm2java
 */
public class TrKurir implements java.io.Serializable {

	private String nik;
	private String nama;
	private String telp;
	private String idJabatan;
	private String noKendaraan;
	private String kodeCabang;
	private String kodePerwakilan;
	private Date tglMasuk;
	private String keterangan;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TrKurir() {
	}

	public TrKurir(String nik) {
		this.nik = nik;
	}

	public TrKurir(String nik, String nama, String telp, String idJabatan, String noKendaraan, String kodeCabang,
			String kodePerwakilan, Date tglMasuk, String keterangan, Date tglCreate, Date tglUpdate, Integer flag) {
		this.nik = nik;
		this.nama = nama;
		this.telp = telp;
		this.idJabatan = idJabatan;
		this.noKendaraan = noKendaraan;
		this.kodeCabang = kodeCabang;
		this.kodePerwakilan = kodePerwakilan;
		this.tglMasuk = tglMasuk;
		this.keterangan = keterangan;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getNik() {
		return this.nik;
	}

	public void setNik(String nik) {
		this.nik = nik;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public String getTelp() {
		return this.telp;
	}

	public void setTelp(String telp) {
		this.telp = telp;
	}

	public String getIdJabatan() {
		return this.idJabatan;
	}

	public void setIdJabatan(String idJabatan) {
		this.idJabatan = idJabatan;
	}

	public String getNoKendaraan() {
		return this.noKendaraan;
	}

	public void setNoKendaraan(String noKendaraan) {
		this.noKendaraan = noKendaraan;
	}

	public String getKodeCabang() {
		return this.kodeCabang;
	}

	public void setKodeCabang(String kodeCabang) {
		this.kodeCabang = kodeCabang;
	}

	public String getKodePerwakilan() {
		return this.kodePerwakilan;
	}

	public void setKodePerwakilan(String kodePerwakilan) {
		this.kodePerwakilan = kodePerwakilan;
	}

	public Date getTglMasuk() {
		return this.tglMasuk;
	}

	public void setTglMasuk(Date tglMasuk) {
		this.tglMasuk = tglMasuk;
	}

	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
