package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TrPegawai generated by hbm2java
 */
public class TrPegawai implements java.io.Serializable {

	private String nip;
	private String namaPegawai;
	private String telpPeg;
	private String idJabatan;
	private String alamatPeg;
	private String kodeCabang;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TrPegawai() {
	}

	public TrPegawai(String nip) {
		this.nip = nip;
	}

	public TrPegawai(String nip, String namaPegawai, String telpPeg, String idJabatan, String alamatPeg,
			String kodeCabang, Date tglCreate, Date tglUpdate, Integer flag) {
		this.nip = nip;
		this.namaPegawai = namaPegawai;
		this.telpPeg = telpPeg;
		this.idJabatan = idJabatan;
		this.alamatPeg = alamatPeg;
		this.kodeCabang = kodeCabang;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getNip() {
		return this.nip;
	}

	public void setNip(String nip) {
		this.nip = nip;
	}

	public String getNamaPegawai() {
		return this.namaPegawai;
	}

	public void setNamaPegawai(String namaPegawai) {
		this.namaPegawai = namaPegawai;
	}

	public String getTelpPeg() {
		return this.telpPeg;
	}

	public void setTelpPeg(String telpPeg) {
		this.telpPeg = telpPeg;
	}

	public String getIdJabatan() {
		return this.idJabatan;
	}

	public void setIdJabatan(String idJabatan) {
		this.idJabatan = idJabatan;
	}

	public String getAlamatPeg() {
		return this.alamatPeg;
	}

	public void setAlamatPeg(String alamatPeg) {
		this.alamatPeg = alamatPeg;
	}

	public String getKodeCabang() {
		return this.kodeCabang;
	}

	public void setKodeCabang(String kodeCabang) {
		this.kodeCabang = kodeCabang;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
