package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TrSales generated by hbm2java
 */
public class TrSales implements java.io.Serializable {

	private String kodeSales;
	private String namaSales;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TrSales() {
	}

	public TrSales(String kodeSales) {
		this.kodeSales = kodeSales;
	}

	public TrSales(String kodeSales, String namaSales, Date tglCreate, Date tglUpdate, Integer flag) {
		this.kodeSales = kodeSales;
		this.namaSales = namaSales;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getKodeSales() {
		return this.kodeSales;
	}

	public void setKodeSales(String kodeSales) {
		this.kodeSales = kodeSales;
	}

	public String getNamaSales() {
		return this.namaSales;
	}

	public void setNamaSales(String namaSales) {
		this.namaSales = namaSales;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
