package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TtGabungPaketId generated by hbm2java
 */
public class TtGabungPaket implements java.io.Serializable {

	private String id;
	private String idKardus;
	private String idKardusSub;
	private String awb;
	private String kodePerwakilan;
	private String oleh;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TtGabungPaket() {
	}

	public TtGabungPaket(
			String id, 
			String idKardus, 
			String idKardusSub, 
			String awb, 
			String kodePerwakilan, 
			String oleh, 
			Date tglCreate,
			Date tglUpdate, 
			Integer flag) {
		this.id = id;
		this.idKardus = idKardus;
		this.idKardusSub = idKardusSub;
		this.awb = awb;
		this.kodePerwakilan = kodePerwakilan;
		this.oleh = oleh;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getIdKardus() {
		return this.idKardus;
	}

	public void setIdKardus(String idKardus) {
		this.idKardus = idKardus;
	}

	public String getIdKardusSub() {
		return this.idKardusSub;
	}

	public void setIdKardusSub(String idKardusSub) {
		this.idKardusSub = idKardusSub;
	}

	public String getAwb() {
		return this.awb;
	}

	public void setAwb(String awb) {
		this.awb = awb;
	}

	public String getKodePerwakilan() {
		return this.kodePerwakilan;
	}

	public void setKodePerwakilan(String kodePerwakilan) {
		this.kodePerwakilan = kodePerwakilan;
	}

	public String getOleh() {
		return this.oleh;
	}

	public void setOleh(String oleh) {
		this.oleh = oleh;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdKardus() == null ? 0 : this.getIdKardus().hashCode());
		result = 37 * result + (getAwb() == null ? 0 : this.getAwb().hashCode());
		result = 37 * result + (getKodePerwakilan() == null ? 0 : this.getKodePerwakilan().hashCode());
		result = 37 * result + (getOleh() == null ? 0 : this.getOleh().hashCode());
		result = 37 * result + (getTglCreate() == null ? 0 : this.getTglCreate().hashCode());
		result = 37 * result + (getTglUpdate() == null ? 0 : this.getTglUpdate().hashCode());
		result = 37 * result + (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}
	public void print(){
		System.out.println("--tt_gabung_paket--");
		System.out.println(id);
		System.out.println(idKardus);
		System.out.println(awb);
		System.out.println(kodePerwakilan);
		System.out.println(oleh);
		System.out.println(tglCreate);
		System.out.println(tglUpdate);
		System.out.println(flag);
	}
}
