package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TtStatusKurirInId generated by hbm2java
 */
public class TtStatusKurirIn implements java.io.Serializable {

	private String id;
	private String noStrukKurirIn;
	private String idKurir;
	private String status;
	private String penerima;
	private String masalah;
	private String waktuJam;
	private String waktuMenit;
	private String idBarang;
	private Date tanggal;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TtStatusKurirIn() {
	}

	public TtStatusKurirIn(String id, String noStrukKurirIn, String idKurir, String status, String penerima, String masalah,
			String waktuJam, String waktuMenit, String idBarang, Date tanggal, Date tglCreate, Date tglUpdate,
			Integer flag) {
		this.id = id;
		this.noStrukKurirIn = noStrukKurirIn;
		this.idKurir = idKurir;
		this.status = status;
		this.penerima = penerima;
		this.masalah = masalah;
		this.waktuJam = waktuJam;
		this.waktuMenit = waktuMenit;
		this.idBarang = idBarang;
		this.tanggal = tanggal;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getNoStrukKurirIn() {
		return this.noStrukKurirIn;
	}

	public void setNoStrukKurirIn(String noStrukKurirIn) {
		this.noStrukKurirIn = noStrukKurirIn;
	}

	public String getIdKurir() {
		return this.idKurir;
	}

	public void setIdKurir(String idKurir) {
		this.idKurir = idKurir;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPenerima() {
		return this.penerima;
	}

	public void setPenerima(String penerima) {
		this.penerima = penerima;
	}

	public String getMasalah() {
		return this.masalah;
	}

	public void setMasalah(String masalah) {
		this.masalah = masalah;
	}

	public String getWaktuJam() {
		return this.waktuJam;
	}

	public void setWaktuJam(String waktuJam) {
		this.waktuJam = waktuJam;
	}

	public String getWaktuMenit() {
		return this.waktuMenit;
	}

	public void setWaktuMenit(String waktuMenit) {
		this.waktuMenit = waktuMenit;
	}

	public String getIdBarang() {
		return this.idBarang;
	}

	public void setIdBarang(String idBarang) {
		this.idBarang = idBarang;
	}

	public Date getTanggal() {
		return this.tanggal;
	}

	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNoStrukKurirIn() == null ? 0 : this.getNoStrukKurirIn().hashCode());
		result = 37 * result + (getIdKurir() == null ? 0 : this.getIdKurir().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getPenerima() == null ? 0 : this.getPenerima().hashCode());
		result = 37 * result + (getMasalah() == null ? 0 : this.getMasalah().hashCode());
		result = 37 * result + (getWaktuJam() == null ? 0 : this.getWaktuJam().hashCode());
		result = 37 * result + (getWaktuMenit() == null ? 0 : this.getWaktuMenit().hashCode());
		result = 37 * result + (getIdBarang() == null ? 0 : this.getIdBarang().hashCode());
		result = 37 * result + (getTanggal() == null ? 0 : this.getTanggal().hashCode());
		result = 37 * result + (getTglCreate() == null ? 0 : this.getTglCreate().hashCode());
		result = 37 * result + (getTglUpdate() == null ? 0 : this.getTglUpdate().hashCode());
		result = 37 * result + (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}
	public void print(){
		System.out.println("----");
		System.out.println(id);
		System.out.println(noStrukKurirIn);
		System.out.println(idKurir);
		System.out.println(status);
		System.out.println(penerima);
		System.out.println(masalah);
		System.out.println(waktuJam);
		System.out.println(waktuMenit);
		System.out.println(idBarang);
		System.out.println(tanggal);
		System.out.println(tglCreate);
		System.out.println(tglUpdate);
		System.out.println(flag);
	}	
}
