package entity;

// default package
// Generated Jun 22, 2016 9:21:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TtStatusResiBermasalahId generated by hbm2java
 */
public class TtStatusResiBermasalah implements java.io.Serializable {

	private String id;
	private String idBarang;
	private String idKurir;
	private String masalah;
	private Date tglCreate;
	private Date tglUpdate;
	private Integer flag;

	public TtStatusResiBermasalah() {
	}

	public TtStatusResiBermasalah(String id, String idBarang, String idKurir, String masalah, Date tglCreate, Date tglUpdate,
			Integer flag) {
		this.id = id;
		this.idBarang = idBarang;
		this.idKurir = idKurir;
		this.masalah = masalah;
		this.tglCreate = tglCreate;
		this.tglUpdate = tglUpdate;
		this.flag = flag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getIdBarang() {
		return this.idBarang;
	}

	public void setIdBarang(String idBarang) {
		this.idBarang = idBarang;
	}

	public String getIdKurir() {
		return this.idKurir;
	}

	public void setIdKurir(String idKurir) {
		this.idKurir = idKurir;
	}

	public String getMasalah() {
		return this.masalah;
	}

	public void setMasalah(String masalah) {
		this.masalah = masalah;
	}

	public Date getTglCreate() {
		return this.tglCreate;
	}

	public void setTglCreate(Date tglCreate) {
		this.tglCreate = tglCreate;
	}

	public Date getTglUpdate() {
		return this.tglUpdate;
	}

	public void setTglUpdate(Date tglUpdate) {
		this.tglUpdate = tglUpdate;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdBarang() == null ? 0 : this.getIdBarang().hashCode());
		result = 37 * result + (getIdKurir() == null ? 0 : this.getIdKurir().hashCode());
		result = 37 * result + (getMasalah() == null ? 0 : this.getMasalah().hashCode());
		result = 37 * result + (getTglCreate() == null ? 0 : this.getTglCreate().hashCode());
		result = 37 * result + (getTglUpdate() == null ? 0 : this.getTglUpdate().hashCode());
		result = 37 * result + (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}

}
